---
title: "Chapter5 Exercises"
author: "Julian Bernauer"
date: "Last edited: 2025-07-01"
output:
  pdf_document: default
  word_document: default
---



1. Visit https://huggingface.co/docs/transformers/en/index, the home of many transformers models at Hugging Face, a machine learning platform and company. Find out what the CamemBERT model is and give an example of its application.

- CamemBERT is a French language model based on the BERT architecture, designed to understand and generate text in French. It is pre-trained on a large corpus of French text and can be fine-tuned for various natural language processing tasks such as text classification, named entity recognition, and sentiment analysis. 
- An example of its application could be using CamemBERT to classify the sentiment of French tweets as positive, negative, or neutral.


2. Load the quanteda.textmodels package. Go to https://tutorials.quanteda.io/ machine-learning/wordscores/ and replicate the quanteda Wordscores tutorial.


require(quanteda)
require(quanteda.textmodels)
require(quanteda.textplots)
# if needed: remotes::install_github("quanteda/quanteda.corpora"); the other packages are available on CRAN
require(quanteda.corpora)

corp_ger <- download(url = "https://www.dropbox.com/s/uysdoep4unfz3zp/data_corpus_germanifestos.rds?dl=1")
summary(corp_ger)

# tokenize texts
toks_ger <- tokens(corp_ger, remove_punct = TRUE)

# create a document-feature matrix
dfmat_ger <- dfm(toks_ger) %>% 
             dfm_remove(pattern = stopwords("de"))

# apply Wordscores algorithm to document-feature matrix
tmod_ws <- textmodel_wordscores(dfmat_ger, y = corp_ger$ref_score, smooth = 1)
summary(tmod_ws)

# predictions 
pred_ws <- predict(tmod_ws, se.fit = TRUE, newdata = dfmat_ger)

# plot
textplot_scale1d(pred_ws)



3. Install and set up the grafzahl package on your computer. Run ?grafzahl and read the files. Run the basic example provided in the package (‘unciviltweets’ data) and try to
interpret the output.


### Exercise 3 - see https://github.com/gesistsa/grafzahl

# Install grafzahl package
# install.packages("grafzahl")

# Load the package
library(grafzahl)

# Get help documentation
?grafzahl

# Load the unciviltweets example data
data("unciviltweets")

# Examine the data structure
head(unciviltweets)
str(unciviltweets)

# Run the basic grafzahl example
# Train a model to classify civil vs uncivil tweets

library(quanteda)
model1 <- grafzahl(unciviltweets, model_type = "bertweet", model_name = "vinai/bertweet-base")

# Make predictions on the training data
predictions <- predict(model1)

# View the results
head(predictions)


